#!/bin/bash

python3 -m venv venv

source venv/bin/activate

pip install -r requirements.txt

if [[ -z "$1" ]]; then
    echo "Необходимо задать имя файла"
    exit 1
fi

python main.py "$1"

chmod +x processing_status
